name: LTA Daily Entry Lists

on:
  schedule:
    - cron: '0 8 * * *'  # Daily at UTC08:00
  workflow_dispatch:

jobs:
  entries-scrape:
    name: Scrape entry lists
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cypress tournaments scrape
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/tournaments.cy.js
        env:
          CYPRESS_POSTCODE: ${{ secrets.POSTCODE }}
      - name: Cypress entries scrape
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/entries.cy.js
          browser: chrome
          install: false
      - name: Archive entries
        uses: actions/upload-artifact@v4
        with:
          name: entries-results
          path: |
            files/tournaments.csv
            files/entries.csv
      - name: Upload to storage container
        uses: azure/CLI@v1
        with:
          azcliversion: 2.51.0
          inlineScript: |
            az storage blob upload-batch --account-name ltascrape  --sas-token '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}' --destination files --source files --pattern '*.csv' --overwrite
