name: LTA Daily Entry Lists

on:
  schedule:
    - cron: '0 8 * * *'  # Daily at UTC08:00
  workflow_dispatch:

jobs:
  entries-scrape:
    name: Scrape entry lists
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Create files directory
        run: mkdir -p files && chmod 777 files
      - name: Download tournaments.csv from Azure
        uses: azure/CLI@v1
        with:
          azcliversion: 2.51.0
          inlineScript: |
            az storage blob download --account-name ltascrape --sas-token '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}' --container-name files --name tournaments.csv --file files/tournaments.csv
            az storage blob download --account-name ltascrape --sas-token '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}' --container-name files --name combined.csv --file files/combined.csv
            chmod 666 files/*.csv
      - name: Cypress entries scrape
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/entries.cy.js
          browser: chrome
      - name: Archive entries
        uses: actions/upload-artifact@v4
        with:
          name: entries-results
          path: files/entries.csv
      - name: Upload entries to Azure
        uses: azure/CLI@v1
        with:
          azcliversion: 2.51.0
          inlineScript: |
            az storage blob upload --account-name ltascrape --sas-token '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}' --container-name files --name entries.csv --file files/entries.csv --overwrite
