name: LTA Website scrape

on:
  schedule:
    - cron: '0 11 * * FRI'  # At UTC11:00 on Friday
  workflow_dispatch:

jobs:
  cypress-run:
    name: Cypress scrape
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cypress rankings scrape
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/lta-website.cy.js
      - name: Cypress tournaments scrape
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/tournaments.cy.js
          install: false
        env:
          CYPRESS_POSTCODE: ${{ secrets.POSTCODE }}
      - name: Cypress entries scrape
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/entries.cy.js
          browser: chrome
          install: false
      - name: Archive Cypress Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            files/combined.csv
            files/u9.csv
            files/u10.csv
            files/tournaments.csv
            files/entries.csv
      - name: Upload to storage container
        uses: azure/CLI@v1
        with:
          azcliversion: 2.51.0
          inlineScript: |
            az storage blob upload-batch --account-name ltascrape  --sas-token '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}' --destination files --source files --pattern '*.csv' --overwrite
