name: Run NPM Script

on: workflow_dispatch

schedule:
  - cron: '0 11 * * FRI'  # At UTC11:00 on Friday

jobs:
  cypress-run:
    name: Cypress scrape
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cypress lta scrape run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/lta-website.cy.js
