name: LTA Website scrape

on:
  schedule:
    - cron: '0 11 * * FRI'  # At UTC11:00 on Friday
  workflow_dispatch:

jobs:
  cypress-run:
    name: Cypress scrape
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cypress lta scrape run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/lta-website.cy.js
      - name: Archive Cypress Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: |
            combined.csv
            u9csv
            u10.csv
      - name: Upload to storage container
        uses: azure/CLI@v1
        with:
          azcliversion: 2.51.0
          inlineScript: |
            az storage blob upload-batch --account-name ltascrape  --sas-token '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}' --destination files --source files --pattern '*.csv' --overwrite
